name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to private registry
        uses: docker/login-action@v3
        with:
          registry: my-private-registry.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: docker build -t mylgg/react-test -f Dockerfile.dev .
      
      - run: docker run -e CI=true mylgg/react-test npm test
